"""production hardening: HelpfulVote model, tz-aware datetimes, review unique constraint, indexes

Revision ID: 4c16224e4129
Revises: ee4317c6fa13
Create Date: 2026-03-05 20:48:46.377696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c16224e4129'
down_revision = 'ee4317c6fa13'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Create helpful_vote only if it doesn't already exist
    if 'helpful_vote' not in existing_tables:
        op.create_table('helpful_vote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('review_id', 'user_id', name='uq_helpful_vote_review_user')
        )

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('nsfas_accredited',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('recommend',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_review_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_review_user_property', ['user_id', 'property_id'])

    existing_user_cols = {c['name'] for c in inspector.get_columns('user')}
    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'verification_code' not in existing_user_cols:
            batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        if 'verification_code_expires' not in existing_user_cols:
            batch_op.add_column(sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True))
        if 'google_id' not in existing_user_cols:
            batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        if 'oauth_provider' not in existing_user_cols:
            batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_reset_token'), ['reset_token'], unique=False)
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_reset_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('google_id')
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_user_property', type_='unique')
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_property_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('recommend',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('nsfas_accredited',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('helpful_vote')
    # ### end Alembic commands ###
