"""Add home language, address, next of kin to ApplicantProfile

Revision ID: 79e0ddb5bb66
Revises: 9ffc6a96c79a
Create Date: 2026-08-13 08:59:43.332500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e0ddb5bb66'
down_revision = '9ffc6a96c79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('residential_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.drop_column('next_of_kin_email')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('residential_address')
        batch_op.drop_column('home_language')

    # ### end Alembic commands ###
