"""Add bursary table

Revision ID: 7e880c61c6c3
Revises: a7b8c9d0e1f2
Create Date: 2026-08-06 21:40:59.557510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e880c61c6c3'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bursary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('funder', sa.String(length=50), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('amount_value', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('university', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bursary')
    # ### end Alembic commands ###
