"""Add can_manage_university_applications to User

Revision ID: 9ffc6a96c79a
Revises: 7e880c61c6c3
Create Date: 2026-08-12 22:57:31.568281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffc6a96c79a'
down_revision = '7e880c61c6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'can_manage_university_applications', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ))
        batch_op.alter_column('can_manage_university_applications', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_manage_university_applications')

    # ### end Alembic commands ###
